# Generated by Django 3.2.9 on 2025-02-16 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the checkout', max_digits=10, verbose_name='Base Price')),
                ('base_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Base discount percentage to apply', max_digits=5, verbose_name='Base Discount Percentage')),
                ('checkout_content', models.JSONField(default=list, help_text='List of content items for checkout', verbose_name='Checkout Content List')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checkout Configuration',
                'verbose_name_plural': 'Checkout Configurations',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=20, unique=True, verbose_name='Coupon Code')),
                ('description', models.TextField(help_text='Description of the coupon', verbose_name='Description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage to apply', max_digits=5, verbose_name='Discount Percentage')),
                ('is_live_to_list', models.BooleanField(default=True, help_text='Whether the coupon is live and listable', verbose_name='Is Live')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CreditCardCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTopBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('is_live', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('current_step', models.CharField(choices=[('amount', 'Loan Amount'), ('personal', 'Personal Information'), ('kyc', 'KYC Information'), ('professional', 'Professional Information'), ('checkout_page', 'Checkout Page')], default='amount', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_details', models.JSONField(blank=True, null=True)),
                ('personal_info', models.JSONField(blank=True, null=True)),
                ('kyc_info', models.JSONField(blank=True, null=True)),
                ('professional_info', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.user')),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 12, 35, 59, 719411, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('gateway', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Payment gateway response data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loanapp.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_name', models.CharField(default='Untitled Card', max_length=255, verbose_name='Credit Card Name')),
                ('bank_name', models.CharField(default='Unknown Bank', max_length=255, verbose_name='Bank Name')),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual fee in INR', max_digits=10, verbose_name='Annual Fee')),
                ('reward_points', models.TextField(default='', help_text='Description of reward points system', verbose_name='Reward Points')),
                ('banner_image_url', models.URLField(default='', help_text='URL for the card banner image', verbose_name='Banner Image URL')),
                ('referral_url', models.URLField(blank=True, help_text='Affiliate/Referral link for the credit card', null=True, verbose_name='Referral URL')),
                ('features', models.JSONField(default=list, help_text='List of card features and benefits', verbose_name='Features')),
                ('active_status', models.BooleanField(default=True, help_text='Whether the card is currently active', verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this card was added', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this card was last modified', verbose_name='Last Updated')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_cards', to='Loanapp.creditcardcategory', verbose_name='Card Category')),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'db_table': 'credit_cards',
                'ordering': ['card_name'],
            },
        ),
    ]
