# Generated by Django 3.2.9 on 2025-02-19 03:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0003_auto_20250217_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 3, 11, 26, 227084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp_code',
            field=models.CharField(max_length=100),
        ),
    ]
