# Generated by Django 3.2.9 on 2025-02-24 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0005_auto_20250223_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 5, 44, 8, 536077, tzinfo=utc)),
        ),
    ]
