# Generated by Django 3.2.9 on 2025-02-24 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0006_auto_20250224_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontacts',
            name='contacts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 6, 27, 36, 995289, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
