# Generated by Django 3.2.9 on 2025-02-24 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Loanapp', '0007_remove_contact_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 6, 27, 43, 170460, tzinfo=utc)),
        ),
    ]
